### DISCUSSION TITLE
Help running clang-tidy via cpp-linter

### DISCUSSION THREAD

**Discussion by rturrado** [cpp-linter/cpp-linter#128] [General]
I have this GitHub Actions job:

```yml
name: Linters

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  cpp-linters:
    name: "C++ linters"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run C++ linters
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extensions: 'cpp,hpp'
          style: 'file'  # use .clang-format config file
          tidy-checks: ''  # use .clang-tidy config file
          version: 18
      - name: Fail fast
        if: steps.linter.outputs.clang-format-checks-failed > 0
        run: |
          echo "::notice::Try executing 'python3 ./scripts/run_cpp_linters.py .' to fix linter issues."
          exit 1
```

I have just enabled the `tidy-checks` setting that variable to `''`.

I have set `CMAKE_EXPORT_COMPILE_COMMANDS` in the outermost CMakeLists.txt:

```cmake
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
```

clang-tidy seems to work well with the `src` directory but, for the `test` directory, it complains not being able to find some files. Although I'm not really sure what file or files caused the reported errors.

```
  Error: 'emscripten/bind.h' file not found
  Error: 'fmt/ostream.h' file not found
  Error: 'libqasm/tree.hpp' file not found
  Error: 'libqasm/error.hpp' file not found
  Error: 'antlr4-runtime.h' file not found
  Error: 'libqasm/v3x/parse_result.hpp' file not found
  Error: 'fmt/format.h' file not found
  Error: 'antlr4-runtime.h' file not found
  Error: 'libqasm/v3x/CqasmParser.h' file not found
  Error: 'libqasm/v3x/antlr_custom_error_listener.hpp' file not found
  Error: 'libqasm/v3x/antlr_scanner.hpp' file not found
  Error: 'libqasm/v3x/instruction_set.hpp' file not found
  Error: 'libqasm/v3x/resolver.hpp' file not found
  Error: 'libqasm/v3x/syntactic_analyzer.hpp' file not found
  Error: 'fmt/format.h' file not found
  Error: 'gmock/gmock.h' file not found
  Error: 'fmt/format.h' file not found
  Error: 'fmt/format.h' file not found
```

This is the GitHub Actions [output](https://github.com/QuTech-Delft/libqasm/actions/runs/11972878424/job/33380662594).

[Question 1] Any idea how to fix these errors?

---

I have seen similar errors when running the linters locally. And I saw that, depending if I was building with gcc or clang, the `compile_commands.json` would be different and lead to different results when running `clang-tidy`.

[Question 2] Should I add a `compile_commands.json` file to my codebase, and provide it as an input to cpp-linter?

Many thanks!

**Comment by 2bndy5** [comment]
> Any idea how to fix these errors?

This question is not specific to cpp-linter.

I suspect that the generated compilation database does not include any files from the test sources. Are tests compiled as a separate target?

I see your project uses conan to drive test builds. I'm not well versed enough to investigate this. Again, this isn't an issue with cpp-linter, rather this is more of an issue with the generated database regarding test sources (& likely third-party dependencies fetched/built using conan).

**Reply by 2bndy5** [reply]
> Although I'm not really sure what file or files caused the reported errors.

Seems pretty clear which file/line the errors are coming from when you look at the file annotations; check [that workflow's summary](https://github.com/QuTech-Delft/libqasm/actions/runs/11972878424) or the [corresponding PR's diff](https://github.com/QuTech-Delft/libqasm/pull/270/files#annotation_28940585612).

**Reply by rturrado** [reply]
Beautiful, thanks. It looks it's complaining in `include` and `src` files.

**Comment by 2bndy5** [comment]
> Should I add a compile_commands.json file to my codebase, and provide it as an input to cpp-linter?

This is not typically done, but it is a solution if the project only uses 1 target/compiler (& C lib version).

Looking at the workflow, I don't see any command to invoke CMake for generating the compilation database before running cpp-linter. clang-tidy can't find a database that isn't there (after a clean checkout).

**Reply by rturrado** [reply]
I am not building before running the linters. Should I do it in the cpp-linters job so I have the following set up?

1. Build generates compile_commands.json.
2. cpp-linter-action uses the just generated compile_commands.json?

If so, would it matter at all for the cpp-linters-action the build type (Debug/Release) and the compiler (gcc/clang) used? Suppossing tests are built for both build types and compilers.

**Reply by 2bndy5** [reply]
correct.

You'll also want to tell cpp-linter the path where the compilation [`database`](https://cpp-linter.github.io/cpp-linter-action/inputs-outputs/#database) exists:
```yml
name: Linters

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  cpp-linters:
    name: "C++ linters"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate compilation database
        # modify this command as needed
        run: cmake -B build -S src

      - name: Run C++ linters
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extensions: 'cpp,hpp'
          style: 'file'  # use .clang-format config file
          tidy-checks: ''  # use .clang-tidy config file
          version: 18

          database: build # compilation database exists in build folder
          ignore: build # ignore any sources copied by CMake in the build environment

      - name: Fail fast
        if: steps.linter.outputs.clang-format-checks-failed > 0
        run: |
          echo "::notice::Try executing 'python3 ./scripts/run_cpp_linters.py .' to fix linter issues."
          exit 1
```

I also added the [`ignore`](https://cpp-linter.github.io/cpp-linter-action/inputs-outputs/#ignore) option because cpp-linter will try to analyze source files that are found in the build folder (which are typically copied from src by CMake).
