### DISCUSSION TITLE
Can't find std headers

### DISCUSSION THREAD

**Discussion by KungFuDonkey** [cpp-linter/cpp-linter#57] [Q&A] [answered]
Now to my understanding not finding the standard headers is a common issue when using CLang and according to [this](https://localcoder.org/ignore-system-headers-in-clang-tidy) page it is possible to remove these errors on local runs of CLang-tidy by using a script or a database. Now because this is a github action I do not know how to either generate a database for the workspace and I do not know if it is possible to check what kind of error has been thrown by the action. So maybe one of you know how to fix this. 

The link to the Github action is [here](https://github.com/red-panda-productions/speed-dreams/runs/6040741059?check_suite_focus=true) if you want to check out the error for yourself.

EDIT:
After a bit of digging I realised that (most likely) clang is not installed at all and thus there would be missing headers. I tried to fix this by calling a command that would install clang-14, but ubuntu said that such a package does not exist. I switched to clang-12 and installed it again, and then it said that clang was already installed. This means that if you select the clang-14 version there probably is a bug that does not install the clang package. I will make this an [issue](https://github.com/shenxianpeng/cpp-linter-action/issues/51) on your repo.

PS:
The rest of the action is amazing and it was really easy to set up, thank you for making this :D

**Comment by 2bndy5** [comment, marked as answer]
> I do not know if it is possible to check what kind of error has been thrown by the action.

Well, filtering the errors thrown by clang-tidy is not an option, and it isn't a feature that we plan to add.

> I do not know how to either generate a database for the workspace

This problem is rather easy. Just run CMake with the option to save the generated compilation database.
```
cmake -Bbuild src -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
```
Then specify to the action where the database exists using the `database` option.

<details><summary>Full example</summary>

```yml
cpp-linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate compilation database
        run: mkdir build && cmake -Bbuild src -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: run linter as action
        uses: shenxianpeng/cpp-linter-action@master
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files-changed-only: false
          # to ignore all build folder contents
          ignore: build
          # indicate where the database is located
          database: build
          version: 14

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        # for actual deployment
        # run: exit 1
```
</details>

Clang-tidy should now be able to use the generated database and hopefully find the `stddef.h`.

I noticed that repo only runs CMake on a workflow that uses Windows. Unfortunately, Windows OS isn't supported for this action; it is supported by the action's src code, but the nature of using a docker image for the action limits workflow runners to Ubuntu only (per GitHub - not something we can control). This is why I design the action's src code to also be used as a python package (which should work on Windows-based workflows).

Here's an example of the action used as a python package.

```yml
      - uses: actions/setup-python@v3
      - name: Install clang-tools
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "14"

      - name: Install linter package
        run: python3 -m pip install git+https://github.com/shenxianpeng/cpp-linter-action

      - name: Generate compilation database  
        run: mkdir build && cmake -Bbuild src -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: run linter as package
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # --version arg is useless on Windows - it will use whatever version is installed
        # --ignore the build/* artifacts generated by CMake
        # --database indicates the path of the generated database
        run: python3 -m cpp_linter.run --ignore=build --database=build --thread-comments=true

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: echo "Some files failed the linting checks!"
        # for actual deployment
        # run: exit 1
```

**Reply by KungFuDonkey** [reply]
Okay thank you for thinking with me! It is really appreciated. The question I now have is why my repo can find stddef on version 12 but it can't on version 14

**Reply by 2bndy5** [reply]
> why my repo can find stddef on version 12 but it can't on version 14

This seems like question for the LLVM project. This action simply executes clang-tidy under the **conditions that you create**. I'd like to remind you that v14.0.1 was released only 3 days ago (v14.0.0 was 24 days ago), maybe there's a problem with the v14.0.0 release. This action is using v14.0.0 only. You could use the action as a python package (example outlined in my last comment) to get v14.0.1 installed instead of v14.0.0

I see that your workflow is still not generating a compilation database.
```yml
      - name: Generate compilation database  
        run: mkdir build && cmake -Bbuild src -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
```
This must be done on the runner since CMake uses absolute paths in the resulting database. Alternatively (& not highly recommended), you could create your own compilation database (as a txt file - see clang-tidy docs for more info), but the path to the std libs (`-I` arg) must correspond to the runner's File System (not your local dev env FS). We have an example of [a txt database in our demo folder](https://github.com/shenxianpeng/cpp-linter-action/blob/master/demo/compile_flags.txt), but it hasn't been tested with v14.

**Reply by KungFuDonkey** [reply]
>
> I see that your workflow is still not generating a compilation database.
>

Yes I will work on it now and keep you posted on the progress.

>
>  I'd like to remind you that v14.0.1 was released only 3 days ago (v14.0.0 was 24 days ago), maybe there's a problem with the v14.0.0 release. 
>

Sorry I missed this, I couldn't find the release dates. I'm very new to clang and llvm, but I will keep it in mind.

**Reply by KungFuDonkey** [reply]
It worked on windows, but the clang package was already installed. I tried to install the clang version 12 with the action you mentioned, but it asked me to override files and I can't specify user input anywhere. I ran it anyway and it seems to work, but something else broke. Github will display the formatting errors, but not the tidy warnings. I do not know why this is, might it have something to do with running it as a python package on windows?

EDIT:
It does say it is trying to create them, but nothing shows up in the Files changed tab of github.

![image](https://user-images.githubusercontent.com/43845930/163674478-3c2cb57a-f7df-4646-9079-3ee83d6e865c.png)

![image](https://user-images.githubusercontent.com/43845930/163674512-08189bfd-f64e-4baa-81f2-98ec11e38355.png)

EDIT 2:
It can create thread comments, so it does have access to the repo I guess?
![image](https://user-images.githubusercontent.com/43845930/163675469-613c8608-80a5-4c18-ba08-66320a7f09df.png)

**Reply by 2bndy5** [reply]
@KungFuDonkey Looks like the [windows-latest (aka windows-2022) runners include LLVM v13.0.1](https://github.com/actions/virtual-environments/blob/win22/20220410.1/images/win/Windows2022-Readme.md#installed-software).

I'm still looking into descrepencies about the action's output. I don't know of a way to specify user input. On Linux I'd try appending a `-y` to the CLI cmd, but that's not a solid solution by any means. Personally, I just hit this error (on the private test repo):
```
Would you like to replace the existing file:
  Path:     C:\Program Files\LLVM\bin\LLVM-C.dll
  Size:     72309760 bytes (69 MiB)
  Modified: 2022-02-02 17:15:06
with the file from archive:
  Path:     bin\LLVM-C.dll
  Size:     77441024 bytes (74 MiB)
  Modified: 2022-03-23 08:50:28
? (Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? 
```
Since I'm using the KyleMayes/install-llvm-action, there's no way to provide user input. I think [that action's `directory` option](https://github.com/KyleMayes/install-llvm-action#directory) could be used to workaround it though (still investigating).

**Reply by 2bndy5** [reply]
> It does say it is trying to create them, but nothing shows up in the Files changed tab of github.

This has to do with the path separator used in a Windows FS (`\`) whereas github seems to prefer the linux (& URI friendly) separator `/` for creating annotations. I have a fix for this on my fork (PR will be submitted when I can test it more).

### Known caveat about annotating diffs
The file annotations (comments found in the event's diff - aka "Files Changed" tab) will only show the annotations made by the latest event's workflow run.

---
Installing a specific version of clang-tools on a windows runner requires a non-default path (to avoid the user input prompt). However, this means that our action's src code needs to be made aware of this non-default path to the executable binaries. I altered the `--version` arg to accept a path and use it for windows platform. Thus, the following steps work using this alteration:
```yml
  cpp-linter:
    runs-on: windows-latest

    strategy:
      matrix:
        clang-version: ['9','10', '11', '12', '13', '14']
        repo: ['2bndy5/cpp-linter-action']
        branch: ['supporting-windows-runner']
      fail-fast: false

    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install clang-tools
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ matrix.clang-version }}
          directory: ${{ runner.temp }}/llvm

      - name: Install linter package
        run: python3 -m pip install git+https://github.com/${{ matrix.repo }}/@${{ matrix.branch }}

      - name: Generate  compiler database  
        run: mkdir build && cmake -Bbuild src -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: run linter as package
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 -m cpp_linter.run -s=file -i=build -p=build -V=${{ runner.temp }}/llvm/bin --thread-comments=true
```

---
After I have added some code to the test project that uses `#include <cstddef>`, I did get an error about STL headers for clang v9, v10, & v11 (requires clang v12 or newer).
```cpp
#include <cstddef>

size_t dummyFunc(size_t i) { return i; }
```
![image](https://user-images.githubusercontent.com/14963867/163681583-6451c0e1-a3af-46fc-b0ac-fe1ecb5253ce.png)
Obviously (because of the VS studio compiler used), this only happens when using a windows-runner. I don't get this problem on ubuntu runners using the action with its docker image.
