### ISSUE TITLE
optionally exclude suggestions in the PR review (using env var)

### ISSUE THREAD

**Issue by 2bndy5** [cpp-linter/cpp-linter#67]
As I typed that list of caveats, I thought that it might be desirable to have only the PR review's summary comment (with no suggestions shown in the diff). To do that, I would probably support a env var named `CPP_LINTER_PR_REVIEW_NO_SUGGESTION`. That should help reduce PR thread pollution.

_Originally posted by @2bndy5 in https://github.com/cpp-linter/cpp-linter-action/issues/182#issuecomment-1893303567_

**Comment by 2bndy5** [comment]
I think `CPP_LINTER_PR_REVIEW_SUMMARY_ONLY` might be a better env var name. It would be used in workflows like so:
```yml
- uses: cpp-linter/cpp-linter-action@v2
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    CPP_LINTER_PR_REVIEW_SUMMARY_ONLY: true
  with:
    tidy-review: true
```
